version: 2
jobs:
  build:
    working_directory: ~/app
    docker: 
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          command: |
            sudo pip install -r requirements/dev.txt
      - run:
          command: |
            pytest tests
      - store_test_results: 
          path: test-results
